-- Insert sample movies data
INSERT INTO public.movies (tmdb_id, title, year, rating, genre, poster, description, duration, director, movie_cast, trailer, type) VALUES
(550, 'Fight Club', '1999', 8.8, 'Drama, Thriller', 'https://images.unsplash.com/photo-1489599735700-3c39022aeb05?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.', '2h 19m', 'David Fincher', ARRAY['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'], 'https://example.com/fight-club-trailer', 'movie'),
(13, 'Forrest Gump', '1994', 8.8, 'Drama, Romance', 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an IQ of 75.', '2h 22m', 'Robert Zemeckis', ARRAY['Tom Hanks', 'Robin Wright', 'Gary Sinise'], 'https://example.com/forrest-gump-trailer', 'movie'),
(680, 'Pulp Fiction', '1994', 8.9, 'Crime, Drama', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence.', '2h 34m', 'Quentin Tarantino', ARRAY['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'], 'https://example.com/pulp-fiction-trailer', 'movie'),
(238, 'The Godfather', '1972', 9.2, 'Crime, Drama', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.', '2h 55m', 'Francis Ford Coppola', ARRAY['Marlon Brando', 'Al Pacino', 'James Caan'], 'https://example.com/godfather-trailer', 'movie'),
(1399, 'Game of Thrones', '2011', 9.3, 'Action, Adventure, Drama', 'https://images.unsplash.com/photo-1534809027769-b00d750a6340?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'Nine noble families fight for control over the lands of Westeros.', '57m per episode', 'David Benioff', ARRAY['Peter Dinklage', 'Lena Headey', 'Emilia Clarke'], 'https://example.com/got-trailer', 'tv'),
(1396, 'Breaking Bad', '2008', 9.5, 'Crime, Drama, Thriller', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'A high school chemistry teacher turned methamphetamine manufacturer.', '47m per episode', 'Vince Gilligan', ARRAY['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'], 'https://example.com/breaking-bad-trailer', 'tv'),
(27205, 'Inception', '2010', 8.8, 'Action, Sci-Fi, Thriller', 'https://images.unsplash.com/photo-1489599735700-3c39022aeb05?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', '2h 28m', 'Christopher Nolan', ARRAY['Leonardo DiCaprio', 'Marion Cotillard', 'Tom Hardy'], 'https://example.com/inception-trailer', 'movie'),
(603, 'The Matrix', '1999', 8.7, 'Action, Sci-Fi', 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', '2h 16m', 'The Wachowskis', ARRAY['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], 'https://example.com/matrix-trailer', 'movie'),
(157336, 'Interstellar', '2014', 8.6, 'Adventure, Drama, Sci-Fi', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.', '2h 49m', 'Christopher Nolan', ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], 'https://example.com/interstellar-trailer', 'movie'),
(335984, 'Blade Runner 2049', '2017', 8.0, 'Action, Drama, Mystery', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80', 'A young blade runner discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.', '2h 44m', 'Denis Villeneuve', ARRAY['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'], 'https://example.com/blade-runner-trailer', 'movie');