// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atddqgslrvuxvlwftbcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0ZGRxZ3NscnZ1eHZsd2Z0YmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTM2MzgsImV4cCI6MjA2NTU2OTYzOH0.BqH_aul1hteMNnrCJ3PIlnpA41FuOsEWEri3tUx-g3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);